import type { Metadata } from "next";
import Link from "next/link";

const BASE_URL = "https://projectcontext.co";
const CANONICAL = "/use-cases/ai-project-planning";
const TITLE = "AI Project Planning — Roadmaps, Milestones & Tasks Generated by AI";
const DESCRIPTION =
  "Saarthi Workflow turns an approved PRD into a sequenced roadmap, 3–7 milestones with dependencies and target dates, and a full task board — automatically. No planning meetings, no copy-paste.";

export const metadata: Metadata = {
  title: TITLE,
  description: DESCRIPTION,
  alternates: { canonical: CANONICAL },
  openGraph: {
    title: TITLE,
    description: DESCRIPTION,
    url: `${BASE_URL}${CANONICAL}`,
  },
  keywords: [
    "AI project planning",
    "AI roadmap generator",
    "AI sprint planning",
    "AI milestone planning",
    "AI project manager tool",
    "AI task breakdown",
    "AI task management",
    "automated project planning",
    "AI agile planning",
    "AI engineering roadmap",
  ],
};

const steps = [
  {
    n: "01",
    title: "Approve the PRD",
    body: "The Project Manager agent waits for a human-approved PRD before doing anything. It refuses to plan from an unapproved spec — no planning on a moving target.",
  },
  {
    n: "02",
    title: "Milestones sequenced",
    body: "The AI Project Manager reads the approved PRD and produces 3–7 milestones ordered chronologically, with priorities, target dates, and dependency relationships.",
  },
  {
    n: "03",
    title: "Tasks broken down",
    body: "The AI Tech Lead decomposes each milestone into 3–7 concrete tasks. Each task gets acceptance criteria, an effort estimate, and a priority. They land directly on your board.",
  },
  {
    n: "04",
    title: "Team assigns and ships",
    body: "The board is ready. Assign tasks to engineers, track progress, and chat with the AI Architect when you hit architectural questions — all in the same workspace.",
  },
];

const capabilities = [
  { title: "Gate-kept planning", body: "The Project Manager won't touch a PRD that hasn't been approved. The gate is enforced in the workflow, not by convention." },
  { title: "Dependency-aware milestones", body: "Milestones are sequenced with explicit dependency tracking. If milestone 3 depends on milestone 1, the plan says so." },
  { title: "Date-aware scheduling", body: "Target dates are set relative to today, accounting for milestone dependencies and effort estimates — not arbitrary placeholders." },
  { title: "Acceptance criteria on every task", body: "Every task the Tech Lead creates includes acceptance criteria — the definition of done is written before work starts." },
  { title: "Effort estimates", body: "Tasks include S/M/L effort estimates based on the complexity of the requirement. Not perfect, but a starting point your team can calibrate." },
  { title: "Board-ready output", body: "Tasks land directly on your project board — no CSV import, no copy-paste. Filter by milestone, assignee, or priority immediately." },
];

const faqs = [
  {
    q: "What is AI project planning?",
    a: "AI project planning uses artificial intelligence to automatically convert product requirements into structured roadmaps, milestones, and task lists. Saarthi Workflow uses two AI agents for this: the Project Manager agent sequences milestones from an approved PRD, and the Tech Lead agent breaks each milestone into board-ready tasks with acceptance criteria.",
  },
  {
    q: "How does Saarthi Workflow generate a roadmap from a PRD?",
    a: "Once a PRD is approved in Saarthi Workflow, the AI Project Manager agent reads the full document and produces 3–7 milestones with priorities, target dates, and dependency relationships. The Tech Lead agent then decomposes each milestone into 3–7 tasks. The entire process takes under a minute.",
  },
  {
    q: "Can I use Saarthi Workflow for sprint planning?",
    a: "Yes. The task board in Saarthi Workflow organises tasks by milestone, effort estimate, and priority — exactly the inputs you need for sprint planning. Assign tasks to engineers, set a sprint scope from the milestone backlog, and track progress in the same workspace.",
  },
  {
    q: "Does the AI project planner understand technical dependencies?",
    a: "The AI Project Manager understands dependencies between milestones and sequences them accordingly. The AI Architect agent can answer architecture questions grounded in your actual codebase — it indexes your repositories and cites specific files when answering.",
  },
  {
    q: "What if I want to change the plan the AI generated?",
    a: "Everything the AI generates is editable. You can reorder milestones, change target dates, add tasks, or ask the Project Manager agent to re-sequence after you update the PRD. The AI plan is a starting point, not a locked constraint.",
  },
];

const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "WebPage",
      "@id": `${BASE_URL}${CANONICAL}`,
      url: `${BASE_URL}${CANONICAL}`,
      name: TITLE,
      description: DESCRIPTION,
      isPartOf: { "@id": `${BASE_URL}/#website` },
    },
    {
      "@type": "FAQPage",
      mainEntity: faqs.map((f) => ({
        "@type": "Question",
        name: f.q,
        acceptedAnswer: { "@type": "Answer", text: f.a },
      })),
    },
  ],
};

export default function AIProjectPlanningPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />

      {/* Hero */}
      <section className="mx-auto max-w-6xl px-6 pt-32 pb-20">
        <div className="max-w-3xl">
          <span className="eyebrow">AI project planning</span>
          <h1 className="mt-6 font-display text-[clamp(2.8rem,7vw,6rem)] leading-[0.95] tracking-tight">
            PRD approved.
            <br />
            <em className="italic text-[var(--mk-accent)]">Board ready in 60 seconds.</em>
          </h1>
          <p className="mt-8 max-w-xl text-lg leading-relaxed text-[var(--mk-muted)]">
            Saarthi Workflow's AI Project Manager and Tech Lead agents turn an
            approved spec into a sequenced roadmap, milestones with dependencies,
            and a full task board — automatically. No planning meeting. No
            copy-paste.
          </p>
          <div className="mt-10 flex flex-col gap-4 sm:flex-row sm:items-center">
            <Link
              href="/auth/signup"
              className="inline-block border border-[var(--mk-accent)] bg-[var(--mk-accent)] px-8 py-3 font-mono-mk text-[11px] uppercase tracking-[0.22em] text-black transition-opacity hover:opacity-90"
            >
              plan your first project →
            </Link>
            <Link
              href="/use-cases"
              className="font-mono-mk text-[11px] uppercase tracking-[0.22em] text-[var(--mk-muted)] transition-colors hover:text-[var(--mk-fg)]"
            >
              ← all use cases
            </Link>
          </div>
        </div>
      </section>

      {/* How it works */}
      <section className="mx-auto max-w-6xl px-6 py-20">
        <div className="marketing-rule mb-16" />
        <span className="eyebrow">how it works</span>
        <h2 className="mt-6 font-display text-4xl leading-tight sm:text-5xl">
          Spec to board in four steps.
        </h2>
        <div className="mt-16 grid gap-px overflow-hidden border border-[var(--mk-line)] bg-[var(--mk-line)] sm:grid-cols-2">
          {steps.map((s) => (
            <div key={s.n} className="bg-[var(--mk-bg)] p-8">
              <span className="font-mono-mk text-xs text-[var(--mk-accent)]">{s.n}</span>
              <h3 className="mt-4 font-display text-2xl leading-tight">{s.title}</h3>
              <p className="mt-3 text-sm leading-relaxed text-[var(--mk-muted)]">{s.body}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Capabilities */}
      <section className="mx-auto max-w-6xl px-6 py-20">
        <div className="marketing-rule mb-16" />
        <span className="eyebrow">capabilities</span>
        <h2 className="mt-6 font-display text-4xl leading-tight sm:text-5xl">
          Plans that hold.
          <br />
          <em className="italic text-[var(--mk-accent)]">Gates that stick.</em>
        </h2>
        <div className="mt-16 grid gap-px overflow-hidden border border-[var(--mk-line)] bg-[var(--mk-line)] sm:grid-cols-2 lg:grid-cols-3">
          {capabilities.map((c) => (
            <div key={c.title} className="bg-[var(--mk-bg)] p-8">
              <h3 className="font-display text-xl leading-tight">{c.title}</h3>
              <p className="mt-3 text-sm leading-relaxed text-[var(--mk-muted)]">{c.body}</p>
            </div>
          ))}
        </div>
      </section>

      {/* FAQ */}
      <section className="mx-auto max-w-6xl px-6 py-20">
        <div className="marketing-rule mb-16" />
        <span className="eyebrow">faq</span>
        <h2 className="mt-6 font-display text-4xl leading-tight sm:text-5xl">
          Common questions.
        </h2>
        <div className="mt-12 divide-y divide-[var(--mk-line)] border border-[var(--mk-line)]">
          {faqs.map((f) => (
            <div key={f.q} className="px-8 py-6">
              <h3 className="font-display text-lg leading-snug">{f.q}</h3>
              <p className="mt-3 text-sm leading-relaxed text-[var(--mk-muted)]">{f.a}</p>
            </div>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section className="mx-auto max-w-6xl px-6 py-20">
        <div className="marketing-rule mb-16" />
        <div className="flex flex-col items-start gap-6 sm:flex-row sm:items-center sm:justify-between">
          <h2 className="font-display text-4xl leading-tight sm:text-5xl">
            Ship the plan
            <br />
            <em className="italic text-[var(--mk-accent)]">before the meeting ends.</em>
          </h2>
          <Link
            href="/auth/signup"
            className="shrink-0 border border-[var(--mk-accent)] bg-[var(--mk-accent)] px-8 py-3 font-mono-mk text-[11px] uppercase tracking-[0.22em] text-black transition-opacity hover:opacity-90"
          >
            get started free →
          </Link>
        </div>
      </section>
    </>
  );
}
