version = 0.1

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
stack_name              = "project-context-foundation-staging"
s3_bucket               = "project-context-sam-deployments"
s3_prefix               = "project-context-foundation-staging"
region                  = "ap-south-1"
capabilities            = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
confirm_changeset       = true
fail_on_empty_changeset = false
parameter_overrides     = "ProjectName=project-context EnvironmentName=staging"
