import type { Metadata } from "next";
import Link from "next/link";

const BASE_URL = "https://projectcontext.co";
const CANONICAL = "/use-cases/ai-prd-generator";
const TITLE = "AI PRD Generator — Write Product Requirements Documents with AI";
const DESCRIPTION =
  "OlmoWorks's AI Analyst agent writes complete Product Requirements Documents from a single idea. Problem statement, goals, user stories, acceptance criteria, and success metrics — drafted in seconds, edited in place.";

export const metadata: Metadata = {
  title: TITLE,
  description: DESCRIPTION,
  alternates: { canonical: CANONICAL },
  openGraph: {
    title: TITLE,
    description: DESCRIPTION,
    url: `${BASE_URL}${CANONICAL}`,
  },
  keywords: [
    "AI PRD generator",
    "AI product requirements document",
    "write PRD with AI",
    "automated PRD",
    "AI product spec",
    "AI product manager tool",
    "PRD writing tool",
    "AI requirements writing",
    "product requirements AI",
  ],
};

const steps = [
  {
    n: "01",
    title: "Describe your idea",
    body: "Type a single sentence — a feature, a problem, a direction. The AI Product Manager agent captures intent and asks the one clarifying question that actually matters.",
  },
  {
    n: "02",
    title: "Analyst drafts the PRD",
    body: "The AI Analyst writes a complete PRD: problem statement, goals, user stories (with personas), functional and non-functional requirements, edge cases, and success metrics. Usually 10–20 pages.",
  },
  {
    n: "03",
    title: "You review and push back",
    body: "Read the draft. Add comments. The Analyst edits surgically — it doesn't rewrite sections you didn't touch. Every version is auto-saved.",
  },
  {
    n: "04",
    title: "Approve to unlock planning",
    body: "When you approve the PRD, the Project Manager agent automatically picks it up and begins milestone sequencing. No copy-paste. No handoff meeting.",
  },
];

const capabilities = [
  { title: "Full PRD structure", body: "Every section you'd expect: problem, goals, user stories, functional requirements, non-functional requirements, constraints, success metrics, and open questions." },
  { title: "Surgical editing", body: "Push back on a section and the Analyst rewrites only that section, leaving the rest intact. Not a full regeneration — targeted updates." },
  { title: "Context-aware", body: "The Analyst loads your product knowledge base before writing. PRDs reference your existing features, users, and architecture — not generic placeholders." },
  { title: "Auto-save", body: "Every draft is saved automatically. Version history is preserved so you can compare revisions or roll back." },
  { title: "Gate-keeping", body: "The Project Manager refuses to plan from an unapproved PRD. The approval gate is enforced — no sneaking a half-baked spec into planning." },
  { title: "Scored output", body: "Every PRD is automatically scored for completeness, clarity, and coverage. You see the score before approving." },
];

const faqs = [
  {
    q: "What is an AI PRD generator?",
    a: "An AI PRD generator is a tool that uses artificial intelligence to draft Product Requirements Documents from a brief description. OlmoWorks's AI Analyst agent writes complete PRDs including problem statements, user stories, acceptance criteria, and success metrics — in seconds rather than days.",
  },
  {
    q: "How is OlmoWorks's AI PRD generator different from ChatGPT?",
    a: "OlmoWorks's Analyst agent is part of a coordinated multi-agent workflow, not a one-shot prompt. It loads your product knowledge base before writing, so the PRD references your real users and existing features. It edits surgically rather than regenerating everything. And the output is gated — a Project Manager agent won't plan from an unapproved spec.",
  },
  {
    q: "What does a PRD generated by OlmoWorks include?",
    a: "OlmoWorks PRDs include: problem statement and context, product goals and non-goals, user personas and user stories, functional requirements, non-functional requirements (performance, security, accessibility), edge cases and constraints, and success metrics. Typical output is 10–20 structured pages.",
  },
  {
    q: "Can I edit the AI-generated PRD?",
    a: "Yes. You can comment on any section and the Analyst will rewrite only that section — it doesn't regenerate the whole document. You can also edit directly. Every change is auto-saved.",
  },
  {
    q: "What happens after the PRD is approved?",
    a: "When you approve the PRD in OlmoWorks, the Project Manager agent automatically picks it up and begins sequencing milestones. No manual handoff — the team keeps moving.",
  },
];

const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "WebPage",
      "@id": `${BASE_URL}${CANONICAL}`,
      url: `${BASE_URL}${CANONICAL}`,
      name: TITLE,
      description: DESCRIPTION,
      isPartOf: { "@id": `${BASE_URL}/#website` },
    },
    {
      "@type": "FAQPage",
      mainEntity: faqs.map((f) => ({
        "@type": "Question",
        name: f.q,
        acceptedAnswer: { "@type": "Answer", text: f.a },
      })),
    },
  ],
};

export default function AIPRDGeneratorPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />

      {/* Hero */}
      <section className="mx-auto max-w-6xl px-6 pt-32 pb-20">
        <div className="max-w-3xl">
          <span className="eyebrow">AI PRD generator</span>
          <h1 className="mt-6 font-display text-[clamp(2.8rem,7vw,6rem)] leading-[0.95] tracking-tight">
            Write a complete PRD
            <br />
            <em className="italic text-[var(--mk-accent)]">from one sentence.</em>
          </h1>
          <p className="mt-8 max-w-xl text-lg leading-relaxed text-[var(--mk-muted)]">
            OlmoWorks's AI Analyst agent writes a complete Product
            Requirements Document — problem, goals, user stories, requirements,
            and success metrics — in seconds. You review, push back, and approve.
            Planning starts automatically.
          </p>
          <div className="mt-10 flex flex-col gap-4 sm:flex-row sm:items-center">
            <Link
              href="/auth/signup"
              className="inline-block border border-[var(--mk-accent)] bg-[var(--mk-accent)] px-8 py-3 font-mono-mk text-[11px] uppercase tracking-[0.22em] text-black transition-opacity hover:opacity-90"
            >
              generate your first PRD →
            </Link>
            <Link
              href="/use-cases"
              className="font-mono-mk text-[11px] uppercase tracking-[0.22em] text-[var(--mk-muted)] transition-colors hover:text-[var(--mk-fg)]"
            >
              ← all use cases
            </Link>
          </div>
        </div>
      </section>

      {/* How it works */}
      <section className="mx-auto max-w-6xl px-6 py-20">
        <div className="marketing-rule mb-16" />
        <span className="eyebrow">how it works</span>
        <h2 className="mt-6 font-display text-4xl leading-tight sm:text-5xl">
          Four steps from idea to approved spec.
        </h2>
        <div className="mt-16 grid gap-px overflow-hidden border border-[var(--mk-line)] bg-[var(--mk-line)] sm:grid-cols-2">
          {steps.map((s) => (
            <div key={s.n} className="bg-[var(--mk-bg)] p-8">
              <span className="font-mono-mk text-xs text-[var(--mk-accent)]">{s.n}</span>
              <h3 className="mt-4 font-display text-2xl leading-tight">{s.title}</h3>
              <p className="mt-3 text-sm leading-relaxed text-[var(--mk-muted)]">{s.body}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Capabilities */}
      <section className="mx-auto max-w-6xl px-6 py-20">
        <div className="marketing-rule mb-16" />
        <span className="eyebrow">capabilities</span>
        <h2 className="mt-6 font-display text-4xl leading-tight sm:text-5xl">
          Not just a prompt.
          <br />
          <em className="italic text-[var(--mk-accent)]">A proper process.</em>
        </h2>
        <div className="mt-16 grid gap-px overflow-hidden border border-[var(--mk-line)] bg-[var(--mk-line)] sm:grid-cols-2 lg:grid-cols-3">
          {capabilities.map((c) => (
            <div key={c.title} className="bg-[var(--mk-bg)] p-8">
              <h3 className="font-display text-xl leading-tight">{c.title}</h3>
              <p className="mt-3 text-sm leading-relaxed text-[var(--mk-muted)]">{c.body}</p>
            </div>
          ))}
        </div>
      </section>

      {/* FAQ */}
      <section className="mx-auto max-w-6xl px-6 py-20">
        <div className="marketing-rule mb-16" />
        <span className="eyebrow">faq</span>
        <h2 className="mt-6 font-display text-4xl leading-tight sm:text-5xl">
          Common questions.
        </h2>
        <div className="mt-12 divide-y divide-[var(--mk-line)] border border-[var(--mk-line)]">
          {faqs.map((f) => (
            <div key={f.q} className="px-8 py-6">
              <h3 className="font-display text-lg leading-snug">{f.q}</h3>
              <p className="mt-3 text-sm leading-relaxed text-[var(--mk-muted)]">{f.a}</p>
            </div>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section className="mx-auto max-w-6xl px-6 py-20">
        <div className="marketing-rule mb-16" />
        <div className="flex flex-col items-start gap-6 sm:flex-row sm:items-center sm:justify-between">
          <h2 className="font-display text-4xl leading-tight sm:text-5xl">
            Ready to write
            <br />
            <em className="italic text-[var(--mk-accent)]">better PRDs, faster?</em>
          </h2>
          <Link
            href="/auth/signup"
            className="shrink-0 border border-[var(--mk-accent)] bg-[var(--mk-accent)] px-8 py-3 font-mono-mk text-[11px] uppercase tracking-[0.22em] text-black transition-opacity hover:opacity-90"
          >
            get started free →
          </Link>
        </div>
      </section>
    </>
  );
}
